server:
  port: 9000

spring:
  data:
    rest:
      base-path: 'api'

  application:
    name: 'spring-ci-efk'

opentracing:
  jaeger:
    service-name: 'spring_truongbb'
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://localhost:14268/api/traces
